### ISSUE TITLE
Сancels minification

### ISSUE THREAD

**Issue by inomdzhon** [SE7ENSKY/group-css-media-queries#15]
I use `stylus` and after them compiled run this plugin. When I push to production, I compress css code with `stylus` opportunity, but `group-css-media-queries` uncompressed code. And now I need install one more dependencies (like gulp-cssnano) and compress code after plugin completed for fix this.

Have another solution?

**Comment by krtcom** [comment]
I have very similar problem using `grunt`, `less` and this plugin: [less-group-css-media-queries](https://github.com/bassjobsen/less-plugin-group-css-media-queries)
When I use compress as one of my options

```
options: {
    compress: true
}
```

the output file is not compressed. When I don't use `group-css-media-queries` the output is compressed as expected

**Comment by ivankravchenko** [comment]
Compression should go after this module's processing.
In other words, processing steps usually look like: execute preprocessor (stylus, less, ...), execute postprocessors (postcss, group-css-media-queries, ..., _minimize_).

**Comment by inomdzhon** [comment]
@ivankravchenko understood. Thanks.
