### ISSUE TITLE
Wrong order of media queries

### ISSUE THREAD

**Issue by Narretz** [SE7ENSKY/group-css-media-queries#4]
I posted this to the grunt repo, but it actually belongs here.

Original: https://github.com/Se7enSky/grunt-group-css-media-queries/issues/3

I have the following css:

```
@media (min-width: 992px) {
  .padded {
    padding: 0 20px;
  }
}
@media (min-width: 480px) {
  .button-small {
    padding: 0 12px 0 15px;
  }
}
@media (min-width: 992px) {
  .button-small {
    padding: 0 25px;
  }
}
```

Grouped, this ends up as:

```
@media (min-width: 992px) {
  .padded {
    padding: 0 20px;
  }

  .button-small {
    padding: 0 25px;
  }
}

@media (min-width: 480px) {
  .button-small {
    padding: 0 12px 0 15px;
  }
}
```

min-width: 480px must come before min-width: 920px, otherwise it overwrites it.

**Comment by Narretz** [comment]
Forgot to tell you that it works very well now. Thanks! 😃

**Comment by ivankravchenko** [comment]
Thank you!
