### ISSUE TITLE
Is there something similar for Javascript?

### ISSUE THREAD

**Issue by bserem** [SE7ENSKY/group-css-media-queries#6]
I love this gulp plugin. It allows me to seperate my sass files the way I want (smacss) and the result is simply working.

I'm looking for something similar for Javascript files. I want to split all my js files smacss way, but in the end I'll have countless of $(document).ready lines in the final js file.
Does anybody now of somthing similar to this plugin but for javascript?

Thanks in advance and sorry for hijacking the issue queue :$

**Comment by ivankravchenko** [comment]
@bserem, you have so nice suggestion!
I can't find ready-to-use solution.
It is pretty easy to write but nearly impossible to guarantee full bulletproof-ness of results. In general, input code must be a valid JavaScript.
If you need one, I can allocate some time writing it. Of course, I would be happy to see your contributions.

**Comment by bserem** [comment]
@ivankravchenko thanks for replying. Please don't spend time on it, I was just wondering if there was something out there that you knew about.

I am not confident with creating my own gulp automations, but given there is time from work I'm gonna invest some time on it.

Thanks again ;)
